[build]
target = "aarch64-unknown-none-softfloat"

[target.aarch64-unknown-none-softfloat]
linker = "aarch64-none-elf-ld"
rustflags = [
    "-C", "link-arg=-Tkernel/kernel.ld",
    "-C", "link-arg=--gc-sections",
    "-Z", "higher-ranked-assumptions"
]

[expand]
theme = "Catppuccin Mocha"
pager = true